import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AlejandriAR - La biblioteca de novelas y recursos PDF',
  description: 'Accede a materiales educativos gratuitos: Educación Sexual Integral (ESI), guías de enfermería, primeros auxilios, recursos LGBT, salud mental y más. Biblioteca digital con PDFs educativos de calidad.',
  keywords: [
    'Educación Sexual Integral',
    'ESI',
    'Materiales educativos',
    'Enfermería',
    'Primeros Auxilios',
    'PDF educativos',
    'AlejandriAR',
    'LGBT',
    'Ayuda LGBT',
    'GUIA TRANS',
    'Adolescencia trans',
    'Adolescencia lgbt',
    'Recursos y ayuda para LGBT',
    'Recursos para enfermeria',
    'Salud mental',
    'Psiquatria',
    'Como detectar un abuso sexual',
    'libros',
    'cuentos',
    'novelas',
    'libros en pdf',
    'pdf libros', 
    'cuentos en pdf',
    'novelas en pdf',
    'biblioteca digital',
    'recursos educativos gratuitos',
    'material didáctico',
    'guías de estudio',
    'recursos académicos',
    'biblioteca virtual',
    'material de consulta',
    'recursos para estudiantes',
  ],
  authors: [{ name: 'AlejandriAR', url: 'https://alejandriar.vercel.app/' }],
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title: 'AlejandriAR - Biblioteca de archivos PDF de la Universidad, ESI, Enfermería, Primeros Auxilios, y mucho más.',
    description: 'Encuentra recursos clave como Educación Sexual Integral, guías de enfermería y mucho más información',
    url: 'https://alejandriar.vercel.app/',
    images: [
      {
        url: 'https://i.postimg.cc/WsZT1cT4/Captura-de-pantalla-2025-02-12-112506.png',
        alt: 'Vista previa de AlejandriAR',
        width: 1200,
        height: 630,
      },
    ],
    type: 'website',
    locale: 'es_AR',
    siteName: 'AlejandriAR',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'AlejandriAR - Materiales Educativos Esenciales',
    description: 'Descubre materiales educativos importantes como guías de ESI y enfermería en AlejandriAR.',
    images: ['https://i.postimg.cc/WsZT1cT4/Captura-de-pantalla-2025-02-12-112506.png'],
  },
  icons: {
    icon: '📚',
    apple: '📚',
  },
  manifest: '/manifest.json',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  }
};

